name: testing
run-name: Testing workflow
on: [ push ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.10", "3.11", "3.12", "3.13" ]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install uv
        run: |
          pip install uv
      - name: Install dependencies
        run: |
           uv sync
      - name: Run pytest
        run: |
          uv run pytest --cov=vcsi.vcsi